### ISSUE TITLE
Review für den Impressum / Startseiten Merge

### ISSUE THREAD

**Issue by FlorianGelb** [FlorianGelb/Web-Engineering-Projekt#9]

**Comment by Jaediknight** [comment]
Die Zusammenführung der beiden Branches "impressum_LuJa" und "startpage_FlKl" erfolgt problemlos nach dem manuellen Zusammenführen der "styles.css" Datei.
Die Funktionalität ist wie geplant gegeben.
Dies bedeutet, dass die Navigation zwischen Impressum und Startseite in beide Richtungen fehlerfrei funktioniert.
Allerdings beinhalten beide Seiten bis jetzt Platzhalter.
Die Platzhalter auf der Startseite werden zu einem späteren Zeitpunkt durch richtigen Inhalt ersetzt.
Das Impressum wird inhaltlich so bleiben wie es ist, da hier, aufgrund der Natur des Projektes, nicht vorgesehen ist, dass echte Kontaktdaten eingetragen werden.
Es könnte eventuell erforderlich sein die Quellen der genutzten Bilddateien genauer anzugeben.
